version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            go get golang.org/x/tools/cmd/goimports
            go get -u golang.org/x/lint/golint
      - run:
          name: Run unit tests
          command: |
            make test

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
